---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 123-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: 123-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: 123-test
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        ports:
        - containerPort: 80
