---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  rules:
  - host: backend-test.skblab.ru
    http:
      paths:
      - backend:
          serviceName: service-nginx
          servicePort: 80
